# load plugins
nop %sh{
	mkdir -p "$kak_config/autoload"
	ln -s "$kak_runtime/autoload" "$kak_config/autoload/standard-library"
}

# indentation
set-option global tabstop 8
set-option global indentwidth 0
# smarttab

# aesthetics
set-face global comment bright-black,default+i
set-face global Whitespace bright-black,default+i
set-face global LineNumbers bright-black,default+i
set-face global WrapMarker bright-black,default

add-highlighter global/ number-lines
add-highlighter global/ show-matching
add-highlighter global/ wrap -marker '↪\'

hook global WinCreate .* %{ kakboard-enable }

# removes trailing whitespace
hook global BufWritePre .* %{
	try %{ execute-keys -itersel -draft '%s\h+$<ret>d' }
}

# lint and format on save
hook global BufWritePre .* %{ evaluate-commands %sh{
	[ -n "$kak_opt_lintcmd" ] && printf "lint\n"
	[ -n "$kak_opt_formatcmd" ] && printf "format\n"
}}


# file-specific options
# c/c++
hook global WinSetOption filetype=(c|cpp) %{
	set-option buffer formatcmd 'astyle -A3 -t -p -H -U -k3 -xC80'
 	set-option window lintcmd "cppcheck --std=posix --enable=all --platform=unix64 --template='{file}:{line}:{column}: {severity}: {message}' 2>&1"
	set-option window tabstop 8
	noexpandtab
}

hook global WinSetOption filetype=(html|css) %{
	set-option window indentwidth 2
	expandtab
}

hook global WinSetOption filetype=js %{
	set-option window lintcmd 'run() { cat "$1" | npx eslint -f unix --stdin --stdin-filename "$kak_buffile";} && run'
	set-option window formatcmd 'standard --fix'
	set-option window indentwidth 2
	expandtab
}

hook global WinSetOption filetype=latex %{
	add-highlighter buffer/ wrap -word -marker '↪\'
	set-option window tabstop 4
	noexpandtab
	spell en-US
}

hook global WinSetOption filetype=markdown %{
	add-highlighter buffer/ wrap -word -marker '↪\'
	set-option window indentwidth 4
	expandtab
	spell en-US
}

hook global WinSetOption filetype=python %{
	set-option window indentwidth 4
	set-option window lintcmd %{ run() { pylint --msg-template='{path}:{line}:{column}: {category}: {msg_id}: {msg} ({symbol})' "$1" | awk -F: 'BEGIN { OFS=":" } { if (NF == 6) { $3 += 1; print } }'; } && run }
	set-option window formatcmd 'black -'
	expandtab
}

hook global WinSetOption filetype=sh %{
	set-option window lintcmd "shellcheck -fgcc -Cnever -x"
	set-option window tabstop 4
	noexpandtab
}

hook global WinSetOption filetype=json %{
	set-option window indentwidth 2
	set-option buffer formatcmd "jq ."
}

hook global WinSetOption filetype=(yaml|toml) %{
	set-option window indentwidth 2
	expandtab
}
